using System;
using System.ComponentModel.DataAnnotations;

namespace FormCapture.Shared.Util
{
    /// <summary>
    /// An abstract class that is a parent class of model classes.
    /// </summary>
    public abstract class Model
    {
        /// <summary>
        /// ID of a model. Generated by Guid.NewGuid().ToString() method.
        /// </summary>
        [Key]
        public string ID { get; set; }

        /// <summary>
        /// Date of row creation.
        /// </summary>
        public DateTime Added { get; set; }

        /// <summary>
        /// Date of last update.
        /// </summary>
        public DateTime Updated { get; set; }
    }
}